compute_environment: LOCAL_MACHINE                
deepspeed_config:
  gradient_accumulation_steps: 8
  gradient_clipping: 1.0
  offload_optimizer_device: "cpu"
  offload_param_device: "cpu"
  zero3_init_flag: true
  zero_stage: 3
  zero3_save_16bit_model: false
  zero_optimization:
    stage: 3
    save_optimizer_state: false
    overlap_comm: true
    contiguous_gradients: true
    reduce_bucket_size: 5e7
    stage3_prefetch_bucket_size: 5e7
    stage3_param_persistence_threshold: 1e5
    stage3_gather_16bit_weights_on_model_save: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_config:
  dynamo_backend: INDUCTOR
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false